In [1]:
import numpy as np
from utils import *
import threading
from layers import *

In [2]:
inS, outS = 5, 10
input = np.random.random((3, inS))
weights = np.random.random((outS, inS))
bias = np.random.random(outS)
input @ weights.T + bias

array([[1.04152355, 2.35022003, 1.99692068, 1.50208564, 1.51342785,
        1.8124456 , 0.95115583, 1.95116723, 1.44766267, 1.9731358 ],
       [2.18348435, 3.86644713, 2.90323025, 2.41167898, 2.53959051,
        2.680982  , 2.23124675, 1.89163222, 2.59366714, 2.46884328],
       [1.21178704, 2.44030819, 1.72736745, 1.53489592, 1.36824531,
        1.8869582 , 1.35545597, 1.48247219, 2.04708566, 1.71627283]])

In [3]:
randDense = Dense(inS, outS)
randDense(input)

array([[0.58821212, 1.26287698, 1.21011795, 2.1548857 , 0.76514086,
        1.24637715, 1.99773818, 1.41556856, 1.15161611, 1.87160363],
       [1.34146791, 2.0859821 , 1.53572981, 4.0071693 , 0.9819903 ,
        3.13693442, 2.52128821, 2.68699963, 2.85644504, 2.80897345],
       [1.0174208 , 1.00370964, 0.6994719 , 2.58034755, 0.51476239,
        2.0203061 , 1.90891747, 1.73683388, 1.68068666, 2.23138663]])

In [4]:
presetDense = Dense(inS, outS, bias=True, presets={'weights': weights, 'bias': bias})
presetDense(input)

array([[1.04152355, 2.35022003, 1.99692068, 1.50208564, 1.51342785,
        1.8124456 , 0.95115583, 1.95116723, 1.44766267, 1.9731358 ],
       [2.18348435, 3.86644713, 2.90323025, 2.41167898, 2.53959051,
        2.680982  , 2.23124675, 1.89163222, 2.59366714, 2.46884328],
       [1.21178704, 2.44030819, 1.72736745, 1.53489592, 1.36824531,
        1.8869582 , 1.35545597, 1.48247219, 2.04708566, 1.71627283]])